### ISSUE TITLE
Code folding in 'new' gitbook style: make it default, make/label icon more prominently

### ISSUE THREAD

**Issue by daaronr** [rethinkpriorities/bookdown-template#8]
Code folding:

Starts unfolded
The ‘fold code icon’ is great … but maybe itneeds a hint … few people will recognize it I think

**Comment by WillemSleegers** [comment]
I changed the default back to starting folded.

The code toggle icon is indeed not very prominent, but it's in the same style as the other buttons so I think that it's best to point to it in the text somewhere if you want the reader to know about it. Also note that in most cases this is not the case because the focus will be on the content, not the code.

**Comment by daaronr** [comment]
yeah, that sounds reasonable. Let's close this issue but remember to note 'where to find the code button' more prominently
